"use client";

import { useState } from "react";

import type { RAGResponse, RetrievalStrategy } from "../lib/types";

export function AskPanel({
  disabled,
  onSubmit,
}: {
  disabled: boolean;
  onSubmit: (question: string, strategy: RetrievalStrategy) => Promise<RAGResponse | undefined>;
}) {
  const [question, setQuestion] = useState("");
  const [strategy, setStrategy] = useState<RetrievalStrategy>("semantic");
  const [history, setHistory] = useState<Array<{ question: string; answer: RAGResponse }>>([]);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const requestedQuestion = question.trim();
    if (requestedQuestion.length === 0) return;
    const answer = await onSubmit(requestedQuestion, strategy);
    if (answer !== undefined) {
      setHistory((items) => [...items, { question: requestedQuestion, answer }]);
      setQuestion("");
    }
  }

  return (
    <section className="modePanel">
      <header>
        <p className="eyebrow">Repository Q&amp;A</p>
        <h2>Ask</h2>
        <p className="muted">Answers and citations are generated by the existing repository-aware RAG API.</p>
      </header>
      <form className="stack" onSubmit={(event) => void submit(event)}>
        <label>
          Question
          <textarea value={question} onChange={(event) => setQuestion(event.target.value)} required maxLength={10_000} />
        </label>
        <label className="inlineControl">
          Retrieval strategy
          <select value={strategy} onChange={(event) => setStrategy(event.target.value as RetrievalStrategy)}>
            <option value="semantic">Semantic</option>
            <option value="hybrid">Hybrid</option>
            <option value="hybrid_rerank">Hybrid + rerank</option>
            <option value="hybrid_symbol">Hybrid + symbol (experimental)</option>
          </select>
        </label>
        <button type="submit" disabled={disabled}>Ask repository</button>
      </form>
      <AskResults history={history} />
    </section>
  );
}

function AskResults({ history }: { history: Array<{ question: string; answer: RAGResponse }> }) {
  if (history.length === 0) return <p className="muted">Q&amp;A history is stored only in this browser tab.</p>;
  return (
    <div className="resultList" aria-live="polite">
      {history.map((item, index) => (
        <AnswerCard key={`${item.question}-${index}`} question={item.question} answer={item.answer} />
      ))}
    </div>
  );
}

export function AnswerCard({ question, answer }: { question: string; answer: RAGResponse }) {
  return (
    <article className="answer">
      <h3>{question}</h3>
      {answer.insufficient_evidence ? <p className="warning">Insufficient repository evidence.</p> : null}
      <p>{answer.answer}</p>
      {answer.citations.length > 0 ? (
        <ul className="citations">
          {answer.citations.map((citation) => (
            <li key={`${citation.relative_path}:${citation.start_line}`}>
              <code>{citation.relative_path}</code> lines {citation.start_line}–{citation.end_line}
            </li>
          ))}
        </ul>
      ) : null}
      {answer.trace_run_id ? <small>Trace {answer.trace_run_id}</small> : null}
    </article>
  );
}
